<?php
# This file was automatically generated by the MediaWiki 1.43.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}




## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "wooms-wiki";
$wgMetaNamespace = "Wooms-wiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://wiki01.kakisoft-practice02.com";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
// $wgLogos = [
// 	'1x' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
// 	'icon' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
// ];

$wgLogos = [
    '1x' => "$wgScriptPath/images/logo.png",
    'icon' => "$wgScriptPath/images/logo.png",
];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "";
$wgPasswordSender = "";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "172.31.1.39";
$wgDBname = "mediawiki";
$wgDBuser = "wikiuser";
$wgDBpassword = "wikisecret";

# MySQL specific settings
$wgDBprefix = "";
$wgDBssl = false;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "ja";

# Time zone
$wgLocaltimezone = "UTC";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = "44447842c485015b71b4288a49f9a592eda299b2002e9e6d5ab27a2b13bfc9a6";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "919054ef15dea191";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions["*"]["createaccount"] = false;
$wgGroupPermissions["*"]["edit"] = false;
$wgGroupPermissions["*"]["read"] = false;
$wgGroupPermissions['sysop']['createaccount'] = true;

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Vector' );

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
// $wgDefaultSkin = "vector";
$wgDefaultSkin = "vector-2022";
// $wgVectorUseLegacy = false;

// # Vector 2022 を新規・既存ユーザに適用
// $wgVectorDefaultSkinVersionForNewAccounts = '2';
// $wgVectorDefaultSkinVersionForExistingAccounts = '2';

# End of automatically generated settings.
# Add more configuration options below.
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'EmbedVideo' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'UserFunctions' );

$wgPFEnableStringFunctions = true;
$wgUFEnableAutoNamespaces = true;

// UserFunctions: MediaWiki 1.43.1 では extension.json 経由のフック登録が効かないため、手動登録
$wgHooks['ParserFirstCallInit'][] = function ( Parser $parser ) {
    $parser->setFunctionHook( 'ifingroup', [ ExtUserFunctions::class, 'ifingroupObj' ], Parser::SFH_OBJECT_ARGS );
};

// アップロードサイズ
$wgMaxUploadSize = 1024 * 1024 * 10;  // 10MB

// AWS S3 アップロード設定
wfLoadExtension( 'AWS' );

$wgAWSRegion     = 'ap-northeast-1';
$wgAWSBucketName = 'kakisoft-wiki-dev';

### ※権限周りの設定は、必ず末尾に記述する。「wfLoadExtension」を実行すると、権限設定が再評価される
$wgGroupPermissions['user']['edit'] = true;
$wgGroupPermissions['user']['createpage'] = true;
$wgGroupPermissions['user']['createtalk'] = true;

# readonly グループの権限は「強制的に無効化」する（revoke = 剥奪）
$wgRevokePermissions['readonly']['edit'] = true;
$wgRevokePermissions['readonly']['createpage'] = true;
$wgRevokePermissions['readonly']['createtalk'] = true;


